### ISSUE TITLE
Multiple notifications?

### ISSUE THREAD

**Issue by davidyang** [taylordaughtry/Craft-Brief#5]
Does this support multiple sections notifying groups?

**Comment by davidyang** [comment]
Is it possible to install multiple versions of the plugin to accomplish this?

**Comment by aladrach** [comment]
That's what we did. We renamed the plugin and references to the name and have 8 instances running perfectly.

**Comment by davidyang** [comment]
Awesome - thanks.

On Fri, Dec 4, 2015 at 2:09 PM, aladrach notifications@github.com wrote:

> That's what we did. We renamed the plugin and references to the name and
> have 8 instances running perfectly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/taylordaughtry/brief/issues/5#issuecomment-162055233.

## 

Fullstack Academy http://fullstackacademy.com/ @fullstack
http://twitter.com/fullstack | LinkedIn
https://www.linkedin.com/in/davidgyang | @dyang
https://twitter.com/dyang

**Comment by taylordaughtry** [comment]
Sorry guys, late to the party! That's what happens when you accidentally turn off notifications on a repo...

Anyway, for any future users reading this, I'm working on this functionality right now; it'll be added in the next version release.

**PS:** Because of the Craft hooks Brief uses, running multiple instances may impact Craft's performance when saving entries. Multiple instances means multiple checks to Brief for sending notifications. Probably not a huge deal, but I thought I'd mention it just in case.

**Comment by davidyang** [comment]
Awesome - thanks @taylordaughtry.  I know the feeling about too many notifications and then missing something months later as well.

**Comment by taylordaughtry** [comment]
This has been fixed in 64baf533ce462952b5ca2b18590a6e429a286a11. User Groups now have notification settings in their permissions, and can be set on a per-group basis.

Let me know if there are any issues!
